spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gtindb
    username: your_db_username
    password: your_db_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect